<#
    Builds Database/ProjectDB/New_Tenant_Database.sql : ONE script that turns an empty
    database into a complete project (tenant) database.

    It is assembled from the sources below, so they stay the single place to edit:
      - servicetenantDB.sql            schema of the service database (tables, procs)
      - 04_MainDb_User_Sync.sql        users/technicians mirrored from MainDB
      - 05_Scope_RowFilter.sql         project/location row filter
      - 06_Customer_Portal.sql         customer portal
      - 07_Locations_Admin.sql         locations administration
      - 08_Backoffice_Technician_Fixes.sql   status sync, spare approvals, conflicts, reports
      - 09_Sales_Order_Despatch.sql    sales order -> despatch -> installation complaint, warranty

    Re-run after changing any of them:
        powershell -ExecutionPolicy Bypass -File .\Build-NewTenantScript.ps1
#>
$ErrorActionPreference = 'Stop'

$here   = Split-Path -Parent $MyInvocation.MyCommand.Path
$api    = Resolve-Path (Join-Path $here '..\..')
$dump   = Join-Path $api 'servicetenantDB.sql'
$output = Join-Path $here 'New_Tenant_Database.sql'

function Read-Script([string]$path) {
    # normalise line ends; drop a BOM if the editor added one
    return ([System.IO.File]::ReadAllText($path) -replace "`r`n", "`n").TrimStart([char]0xFEFF)
}

function Section([string]$title) {
    $line = '=' * 77
    return "`n/* $line`n   $title`n   $line */`n"
}

# ── 1. schema: the dump without CREATE/ALTER DATABASE and USE ───────────────────
$lines = (Read-Script $dump) -split "`n"
$start = [Array]::IndexOf($lines, ($lines | Where-Object { $_ -match '^USE \[(?!master\])' } | Select-Object -First 1))
$end   = -1
for ($i = $lines.Count - 1; $i -gt $start; $i--) {
    if ($lines[$i] -match '^USE \[master\]') { $end = $i; break }
}
if ($start -lt 0 -or $end -le $start) { throw 'Could not find the schema part of servicetenantDB.sql' }

# skip "USE [db]" and its GO
$schema = ($lines[($start + 2)..($end - 1)] -join "`n").Trim()

# Legacy control-plane procs of the dump that do not compile any more. The API uses the
# MainDB versions; leaving them out keeps the run free of error messages.
$brokenLegacyProcs = @('sp_Company_GetPendingInvitations')

$batches = [regex]::Split($schema, '(?m)^GO[ \t]*$')
$kept    = $batches | Where-Object {
    $batch = $_
    -not ($brokenLegacyProcs | Where-Object {
        $batch -match ('(?i)CREATE\s+(OR\s+ALTER\s+)?PROC(EDURE)?\s+\[dbo\]\.\[' + [regex]::Escape($_) + '\]')
    })
}
if (($batches.Count - $kept.Count) -ne $brokenLegacyProcs.Count) { throw 'A proc listed in $brokenLegacyProcs was not found in the dump' }
$schema = (($kept | ForEach-Object { $_.Trim("`n") }) -join "`nGO`n").Trim()
if ($schema -match '(?im)^\s*(CREATE|ALTER)\s+DATABASE\b|^\s*USE\s+\[') {
    throw 'The schema part still contains a database-level statement'
}

# ── 2. the row filter reads the tenant settings instead of its fixed defaults ──
$rowFilter = Read-Script (Join-Path $here '05_Scope_RowFilter.sql')
$defaults  = '(?s)DECLARE @DefaultCompanyId  INT = 1;.*?ORDER BY LocationId\), 1\);'
if ($rowFilter -notmatch $defaults) { throw '05_Scope_RowFilter.sql: settings block not found' }
$rowFilter = [regex]::Replace($rowFilter, $defaults, @'
DECLARE @DefaultCompanyId  INT = (SELECT CompanyId FROM #TenantSettings);
DECLARE @DefaultProjectId  INT = (SELECT ProjectId FROM #TenantSettings);
DECLARE @DefaultLocationId INT = ISNULL((SELECT TOP 1 LocationId FROM dbo.Locations
                                         WHERE ProjectId = @DefaultProjectId AND IsActive = 1
                                         ORDER BY LocationId), 1);
'@)

# ── 3. fixed parts ─────────────────────────────────────────────────────────────
$header = @'
/* =============================================================================
   NEW TENANT (PROJECT) DATABASE  ·  everything in one script
   -----------------------------------------------------------------------------
   GENERATED by Build-NewTenantScript.ps1 — do not edit this file; edit the source
   scripts and rebuild.

   HOW TO USE
     1. Create an EMPTY database, e.g.   CREATE DATABASE FelixProject_C002;
     2. In SSMS select THAT database in the database dropdown.
     3. Fill in "SETTINGS" below.
     4. Execute (F5).
     5. In the application: Settings > Platform Admin > Projects & Databases
        > New Project, point it at this database and press "Test connection".
        (The company and project must exist in MainDB with the ids used here.)

   The script refuses to run on master, on MainDB, or on a database that already
   has service tables. Nothing in MainDB is changed by it.
   ============================================================================= */

SET NOCOUNT ON;
SET NOEXEC OFF;
GO

/* =============================================================================
   SETTINGS — review before running
   ============================================================================= */
IF OBJECT_ID('tempdb..#TenantSettings') IS NOT NULL DROP TABLE #TenantSettings;

CREATE TABLE #TenantSettings
(
    CompanyId       INT           NOT NULL,   -- MainDB.dbo.Companies.CompanyId
    ProjectId       INT           NOT NULL,   -- MainDB.dbo.Projects.ProjectId
    LocationName    NVARCHAR(200) NOT NULL,   -- first location of the project
    LocationCode    NVARCHAR(50)  NULL,
    LocationCity    NVARCHAR(100) NULL,
    CopyLookupsFrom SYSNAME       NULL        -- existing service DB on THIS server to copy
                                              -- statuses / roles / settings from; NULL = defaults
);

INSERT INTO #TenantSettings (CompanyId, ProjectId, LocationName, LocationCode, LocationCity, CopyLookupsFrom)
VALUES (
    0,                  -- <<< CompanyId
    0,                  -- <<< ProjectId
    N'Head Office',     -- <<< first location
    N'HO',
    NULL,
    N'FelixServiceDB'   -- <<< or NULL
);
GO

/* =============================================================================
   SAFETY CHECKS — any failure skips the whole script
   ============================================================================= */
DECLARE @problem NVARCHAR(400);

IF DB_NAME() IN ('master', 'model', 'msdb', 'tempdb')
    SET @problem = 'You are connected to [' + DB_NAME() + ']. Select the new, empty tenant database first.';
ELSE IF OBJECT_ID('dbo.ProjectConnections') IS NOT NULL
    SET @problem = 'Database [' + DB_NAME() + '] is the MAIN database. Select the new, empty tenant database.';
ELSE IF OBJECT_ID('dbo.Complaints') IS NOT NULL OR OBJECT_ID('dbo.Customers') IS NOT NULL
    SET @problem = 'Database [' + DB_NAME() + '] already has service tables. This script is for an EMPTY database; '
                 + 'for an existing one run FelixServiceDB_Migration.sql and scripts 04-07.';
ELSE IF EXISTS (SELECT 1 FROM #TenantSettings WHERE CompanyId <= 0 OR ProjectId <= 0)
    SET @problem = 'Fill in CompanyId and ProjectId in SETTINGS (the ids from MainDB).';
ELSE IF EXISTS (SELECT 1 FROM #TenantSettings
                WHERE CopyLookupsFrom IS NOT NULL AND DB_ID(CopyLookupsFrom) IS NULL)
    SET @problem = 'CopyLookupsFrom names a database that does not exist on this server. Correct it or set it to NULL.';
ELSE IF EXISTS (SELECT 1 FROM #TenantSettings WHERE CopyLookupsFrom = DB_NAME())
    SET @problem = 'CopyLookupsFrom cannot be the new database itself.';

IF @problem IS NOT NULL
BEGIN
    RAISERROR(@problem, 16, 1);
    SET NOEXEC ON;      -- every following batch is compiled but not executed
END
ELSE
    PRINT 'Creating tenant database objects in [' + DB_NAME() + '] ...';
GO
'@

$lookups = @'
/* Lookup / master rows the procs rely on (status ids, role ids, settings, menus).
   ProjectId 0 = shared master row, visible to every project of this database. */
DECLARE @source SYSNAME = (SELECT CopyLookupsFrom FROM #TenantSettings);

IF @source IS NOT NULL
BEGIN
    /* copy with the ORIGINAL ids: several procs use fixed StatusId / RoleId values.
       Columns that point at users are not copied (the users are not). */
    DECLARE @t SYSNAME, @cols NVARCHAR(MAX), @sel NVARCHAR(MAX), @sql NVARCHAR(MAX), @hasIdentity BIT, @found INT;
    DECLARE @tables TABLE (Seq INT IDENTITY(1,1), Name SYSNAME);
    INSERT INTO @tables (Name) VALUES
        ('Roles'), ('ComplaintStatuses'), ('MenuItems'), ('RoleMenuAccess'), ('SystemSettings'), ('AppConfigurations');

    DECLARE cur CURSOR LOCAL STATIC FOR SELECT Name FROM @tables ORDER BY Seq;
    OPEN cur; FETCH NEXT FROM cur INTO @t;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @sql = N'SELECT @n = COUNT(*) FROM ' + QUOTENAME(@source) + N'.sys.tables WHERE name = @t AND schema_id = 1';
        EXEC sp_executesql @sql, N'@t SYSNAME, @n INT OUTPUT', @t = @t, @n = @found OUTPUT;

        IF @found = 0
            PRINT 'Lookup copy: ' + @t + ' not found in ' + @source + ' (skipped)';
        ELSE
        BEGIN
            CREATE TABLE #srcCols (Name SYSNAME);
            SET @sql = N'INSERT INTO #srcCols SELECT c.name FROM ' + QUOTENAME(@source) + N'.sys.columns c '
                     + N'INNER JOIN ' + QUOTENAME(@source) + N'.sys.tables t ON t.object_id = c.object_id '
                     + N'WHERE t.name = @t AND t.schema_id = 1 AND c.is_computed = 0';
            EXEC sp_executesql @sql, N'@t SYSNAME', @t = @t;

            SELECT @cols = STRING_AGG(CAST(QUOTENAME(c.name) AS NVARCHAR(MAX)), N', '),
                   @sel  = STRING_AGG(CAST(
                               CASE WHEN c.name IN ('CompanyId', 'ProjectId', 'LocationId') THEN N'0'
                                    ELSE N's.' + QUOTENAME(c.name) END AS NVARCHAR(MAX)), N', ')
            FROM sys.columns c
            INNER JOIN #srcCols s ON s.Name = c.name
            WHERE c.object_id = OBJECT_ID('dbo.' + @t)
              AND c.is_computed = 0
              AND c.name NOT IN ('ModifiedBy', 'UpdatedBy', 'CreatedBy');

            DROP TABLE #srcCols;

            SET @hasIdentity = CASE WHEN EXISTS (SELECT 1 FROM sys.identity_columns
                                                 WHERE object_id = OBJECT_ID('dbo.' + @t)) THEN 1 ELSE 0 END;

            SET @sql = CASE WHEN @hasIdentity = 1 THEN N'SET IDENTITY_INSERT dbo.' + QUOTENAME(@t) + N' ON; ' ELSE N'' END
                     + N'INSERT INTO dbo.' + QUOTENAME(@t) + N' (' + @cols + N') SELECT ' + @sel
                     + N' FROM ' + QUOTENAME(@source) + N'.dbo.' + QUOTENAME(@t) + N' s; '
                     + N'PRINT ''Lookup copy: ' + @t + N' '' + CAST(@@ROWCOUNT AS VARCHAR(12)) + '' row(s)''; '
                     + CASE WHEN @hasIdentity = 1 THEN N'SET IDENTITY_INSERT dbo.' + QUOTENAME(@t) + N' OFF;' ELSE N'' END;
            EXEC sp_executesql @sql;
        END

        FETCH NEXT FROM cur INTO @t;
    END
    CLOSE cur; DEALLOCATE cur;
END
GO

/* Defaults when nothing was copied. ASSUMED ids: the procs create complaints with
   StatusId 1 and customers with RoleId 4 / technicians with RoleId 3; the other ids
   follow the status NAMES the procs test for. Prefer CopyLookupsFrom. */
IF NOT EXISTS (SELECT 1 FROM dbo.Roles)
BEGIN
    SET IDENTITY_INSERT dbo.Roles ON;
    INSERT INTO dbo.Roles (RoleId, RoleName, Description, IsActive, CompanyId, ProjectId, LocationId) VALUES
        (1, 'Admin',          'Full access',           1, 0, 0, 0),
        (2, 'Manager',        'Manager',               1, 0, 0, 0),
        (3, 'Technician',     'Field technician',      1, 0, 0, 0),
        (4, 'Customer',       'Customer portal user',  1, 0, 0, 0),
        (5, 'Storekeeper',    'Store / inventory',     1, 0, 0, 0),
        (6, 'CompanyAdmin',   'Company administrator', 1, 0, 0, 0),
        (7, 'ServiceManager', 'Service manager',       1, 0, 0, 0);
    SET IDENTITY_INSERT dbo.Roles OFF;
    PRINT 'Roles: default rows created';
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.ComplaintStatuses)
BEGIN
    SET IDENTITY_INSERT dbo.ComplaintStatuses ON;
    INSERT INTO dbo.ComplaintStatuses (StatusId, StatusName, StatusColor, SortOrder, CompanyId, ProjectId, LocationId) VALUES
        (1,  'New',           '#2563EB', 1, 0, 0, 0),
        (2,  'InProgress',    '#D97706', 2, 0, 0, 0),
        (3,  'WorkCompleted', '#16A34A', 3, 0, 0, 0),
        (4,  'Closed',        '#475569', 4, 0, 0, 0),
        (5,  'Assigned',      '#7C3AED', 5, 0, 0, 0),
        (6,  'OnHold',        '#EA580C', 6, 0, 0, 0),
        (10, 'Cancelled',     '#DC2626', 7, 0, 0, 0);
    SET IDENTITY_INSERT dbo.ComplaintStatuses OFF;
    PRINT 'ComplaintStatuses: default rows created (review the ids against your procs)';
END
GO
'@

$location = @'
INSERT INTO dbo.Locations (CompanyId, ProjectId, LocationName, LocationCode, City)
SELECT s.CompanyId, s.ProjectId, s.LocationName, s.LocationCode, s.LocationCity
FROM #TenantSettings s
WHERE NOT EXISTS (SELECT 1 FROM dbo.Locations l
                  WHERE l.CompanyId = s.CompanyId AND l.ProjectId = s.ProjectId);
GO
'@

$footer = @'
/* =============================================================================
   DONE
   ============================================================================= */
DECLARE @company INT, @project INT;
SELECT @company = CompanyId, @project = ProjectId FROM #TenantSettings;

SELECT DB_NAME()                                                        AS TenantDatabase,
       @company                                                         AS CompanyId,
       @project                                                         AS ProjectId,
       (SELECT COUNT(*) FROM sys.tables WHERE is_ms_shipped = 0)         AS Tables,
       (SELECT COUNT(*) FROM sys.procedures WHERE is_ms_shipped = 0)     AS Procedures,
       (SELECT COUNT(*) FROM dbo.Locations WHERE ProjectId = @project)   AS Locations,
       (SELECT COUNT(*) FROM dbo.ComplaintStatuses)                      AS ComplaintStatuses,
       (SELECT COUNT(*) FROM dbo.Roles)                                  AS Roles,
       (SELECT COUNT(*) FROM sys.security_policies WHERE is_enabled = 1) AS RowFilterPolicies;

PRINT 'Tenant database [' + DB_NAME() + '] is ready.';
PRINT 'Next: Settings > Platform Admin > Projects & Databases > point the project at this database and Test connection.';
GO

SET NOEXEC OFF;
GO
IF OBJECT_ID('tempdb..#TenantSettings') IS NOT NULL DROP TABLE #TenantSettings;
GO
'@

# ── 4. assemble ────────────────────────────────────────────────────────────────
$parts = @(
    $header
    (Section '1. SCHEMA  (from servicetenantDB.sql)')
    $schema
    "GO"
    (Section '2. LOOKUP DATA')
    $lookups
    (Section '3. USERS / TECHNICIANS FROM MAINDB  (04_MainDb_User_Sync.sql)')
    (Read-Script (Join-Path $here '04_MainDb_User_Sync.sql'))
    (Section '4. FIRST LOCATION')
    $location
    (Section '5. PROJECT / LOCATION ROW FILTER  (05_Scope_RowFilter.sql)')
    $rowFilter
    (Section '6. CUSTOMER PORTAL  (06_Customer_Portal.sql)')
    (Read-Script (Join-Path $here '06_Customer_Portal.sql'))
    (Section '7. LOCATIONS ADMINISTRATION  (07_Locations_Admin.sql)')
    (Read-Script (Join-Path $here '07_Locations_Admin.sql'))
    (Section '8. BACK-OFFICE / TECHNICIAN FIXES  (08_Backoffice_Technician_Fixes.sql)')
    (Read-Script (Join-Path $here '08_Backoffice_Technician_Fixes.sql'))
    (Section '9. SALES ORDER / DESPATCH / WARRANTY  (09_Sales_Order_Despatch.sql)')
    (Read-Script (Join-Path $here '09_Sales_Order_Despatch.sql'))
    $footer
)

$text = (($parts | ForEach-Object { $_.Trim("`n") }) -join "`n`n") + "`n"

# every batch separator must stand alone on its line
$text = $text -replace "(?m)^[ \t]*GO[ \t]*$", 'GO'

[System.IO.File]::WriteAllText($output, ($text -replace "`n", "`r`n"), (New-Object System.Text.UTF8Encoding($true)))

$lineCount = ($text -split "`n").Count
Write-Host "Written $output ($lineCount lines)"
